apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
  labels:
    type: microk8s-hostpath
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/prometheus-rules

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics
  labels:
    type: microk8s-hostpath
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: templates-volume
  configMap:
    name: alertmanager
  labels:
    type: microk8s-hostpath
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /alertmanager